---
name: publish

# Actions for any tag.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# PYPI_USERNAME
# PYPI_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
    tags:
    - '**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r package-requirements.txt
    - name: Build
      run: |
        pyroma .
        pylint standardize_molecule.py
        python setup.py bdist_wheel
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_TOKEN }}
